include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy
  - maintenance

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  STACK: maintenance
  SERVICES_TO_CHECK: maintenance_${CI_PROJECT_NAME}
  IMAGE_NAME: spotify/docker-gc
  IMAGE_TAG: latest

scheduled-run-stable-branch-develop:
  stage: maintenance
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICE: ${STACK}_${CI_PROJECT_NAME}
  script: relaunch.sh
  only:
    - schedules

scheduled-run-stable-branch-production:
  stage: maintenance
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICE: ${STACK}_${CI_PROJECT_NAME}
  script: relaunch.sh
  only:
    - schedules
