include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/maintenance.yml'

stages:
  - deploy
  - maintenance

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  STACK: maintenance
  IMAGE_NAME: spotify/docker-gc
  IMAGE_TAG: latest
