include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: ${GITLAB_CI_TEMPLATE_REF:-master}
    file: '/deployment.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: ${GITLAB_CI_TEMPLATE_REF:-master}
    file: '/maintenance.yml'

stages:
  - deploy
  - maintenance

variables:
  STACK: maintenance
  IMAGE_NAME: spotify/docker-gc
  IMAGE_TAG: latest
