version: '3.5'

services:
  docker-gc:
    image: ${IMAGE_NAME:-spotify/docker-gc}:${IMAGE_TAG:-latest}
    environment:
      GRACE_PERIOD_SECONDS:
      MINIMUM_IMAGES_TO_SAVE:
      REMOVE_ASSOCIATED_VOLUME:
      EXCLUDE_DEAD:
      DRY_RUN:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - docker-gc-vol:/var/lib/docker-gc
    configs:
      - source: exclude-gc-image
        target: /etc/docker-gc-exclude
      - source: exclude-gc-container
        target: /etc/docker-gc-exclude-containers
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: ${RESTART_DELAY:-1m}
      update_config:
        delay: ${UPDATE_DELAY:-2m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

volumes:
  docker-gc-vol:
    name: ${DOCKER_GC_VOL_NAME:-docker-gc-vol}

configs:
  exclude-gc-image:
    name: ${EXCLUDE_GC_IMAGE_NAME:-exclude-gc-image}
    file: ./config/exclude-gc-image.txt

  exclude-gc-container:
    name: ${EXCLUDE_GC_CONTAINER_NAME:-exclude-gc-container}
    file: ./config/exclude-gc-container.txt
